name: Patchron
on:
    pull_request:
        types: [opened]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: trolit/patchron
            - name: Install modules
              run: yarn
