name: Review PR (gh actions)

on:
    pull_request:
        types:
            - opened

jobs:
    reviewOpenedPull:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  repository: 'trolit/Patchron'
                  ref: 'v1.2.2'

            - run: npm ci --only=production

            - run: npm start
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # or secrets.PAT
                  NODE_ENV: 'production'
                  RULES_CONFIGURATION_PATH: 'src/config/rules'
                  # available options: https://github.com/trolit/Patchron#2-configuration
