name: Review PR (gh actions, relative paths)

on:
    pull_request:
        types:
            - opened

jobs:
    reviewOpenedPull:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  repository: 'trolit/Patchron'
                  ref: 'test3'

            - run: npm ci --only=production

            - run: npm start
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # or secrets.PAT
                  NODE_ENV: 'production'
                  RULES_CONFIGURATION_URL: 'https://raw.githubusercontent.com/trolit/Patchron/feature/configure-rules-by-path/.github/examples/rulesByRelativePaths.json'
                  # available options: https://github.com/trolit/Patchron#2-configuration
